### ISSUE TITLE
Container to Container connection may break after apps are restarted

### ISSUE THREAD

**Issue by iamejboy** [cloudfoundry/cf-networking-release#42] opened 2018-06-26 00:37 UTC
Thanks for submitting an issue to `cf-networking-release`. We are always trying to improve! To help us, please fill out the following template.

## Issue

Container to Container connection may break after apps are restarted.

## Context

We put C2C to a test and ran a script similar to below to make sure that C2C runs as expected.

while true; do
   add policy app_cat to app_dog on port 8080
   restart both app_cat & app_dog
   while Connection fail; do
       Test connection app_cat to app_dog on port 8080
   done
   remove policy app_cat to app_dog on port 8080
done

Script just runs normally completing loop over and over, and at some point, below happens:

What we have found out, It always happens that it will be stuck on inner loop at one point.

 while Connection fail; do
   Test connection app_cat to app_dog on port 8080
 done
 
Means at that point, policy is in placed but connection continue to fail.

## Steps to Reproduce

- We ran a script similar to below:

while true; do
   add policy app_cat to app_dog on port 8080
   restart both app_cat & app_dog
   while Connection fail; do
     Test connection app_cat to app_dog on port 8080
   done
   remove policy app_cat to app_dog on port 8080
done

- 1 instance for both app_cat and app_dog
- Issue can be observed in v1.9.0 and v1.13.0 + silk v0.30
- We have 3 available diego-cell when this was tested

## Expected result

C2C should not break after both apps are successfully restarted with policy in placed.

## Current result

- Observations:

First time stuck on loop:
Old
this is cat IP CF_INSTANCE_INTERNAL_IP=10.78.10.15
this is dog IP CF_INSTANCE_INTERNAL_IP=10.77.65.113
New
this is cat IP CF_INSTANCE_INTERNAL_IP=10.78.23.62
this is dog IP CF_INSTANCE_INTERNAL_IP=10.78.10.16

Second time stuck on loop:
Old
this is cat IP CF_INSTANCE_INTERNAL_IP=10.78.23.247
this is dog IP CF_INSTANCE_INTERNAL_IP=10.77.65.142
New
this is cat IP CF_INSTANCE_INTERNAL_IP=10.78.10.200
this is dog IP CF_INSTANCE_INTERNAL_IP=10.78.23.248

As observed above it happens when new destination app_dog goes to source app_cat previous host-container(diego-cell)
and their IP is one just 1 diff only

e.g.
Old
this is cat IP CF_INSTANCE_INTERNAL_IP=10.78.10.15

New
this is dog IP CF_INSTANCE_INTERNAL_IP=10.78.10.16

## `name of issue` screenshot

[if relevant, include a screenshot]

**Comment by adobley** [comment] 2018-06-29 16:34
@iamejboy We attempted to reproduce this issue with a fresh 1.9 install of cf-networking-release, but were unable to cause the issue.

We suspect that it is due to the positioning of the `vpa` rule at a position other than `0`. If it is not inserting at the top we suspect that there might be an error occurring inside the vxlan policy agent.

Are there any error logs with the vxlan policy agent on the cell?

**Comment by iamejboy** [comment] 2018-07-02 03:45
@adobley , thanks for looking into it. This behavior happens by chance like once or twice in 1 day. You may need to run the script indefinitely until you reproduce it.  Did you happen to do it with this condition? . 

-  1 instance for both source_container and destination_container
-  Issue can be observed in v1.9.0 and v1.13.0 + silk v0.30
-  3 available diego-cell when this was tested.

I do not see any error logs on vxlan policy agent on the cell on time I reproduced it. But I can reproduce it again to make sure.

See my previous test script logs:
https://cloudfoundry.slack.com/archives/C0JV2NPJ4/p1530018064000534?thread_ts=1529574722.000114&cid=C0JV2NPJ4

 Destination container IPtables, vpa should be on third line
https://cloudfoundry.slack.com/archives/C0JV2NPJ4/p1530018407000627?thread_ts=1529574722.000114&cid=C0JV2NPJ4

**Comment by christianang** [comment] 2018-07-02 16:31
@adobley and I did run this overnight and we didn't happen to reproduce against 1.9.0 using two applications (one source and one destination) on two diego cells.

If you can reproduce it again I would be curious to know if the vpa chain is ever updated. When the vxlan-policy-agent polls it will destroy the old vpa chain and creates a new vpa chain with a new timestamp i.e `vpa-<current-time>`. If you watch the iptables for 10 seconds or so let us know if you see if the chain name changes or not. If it doesn't then there might be a bug with recreating the vpa chain.

**Comment by iamejboy** [comment] 2018-07-03 00:36
The very interesting part is that is always happen when new dest_container goes to previous src_container host-cell and their IP has 1 or 2 difference. I managed to reproduced this again.

Here:

this is cat IP CF_INSTANCE_INTERNAL_IP=10.255.74.32
this is dog IP CF_INSTANCE_INTERNAL_IP=10.255.5.165
Connection to 10.255.5.165 8080 port [tcp/http-alt] succeeded!
Time to succeed connection 1
Removing network policy for app rpaas_c2c_cat in org RPAAS / space monitor-stg as sv-ops-rpaas-mon...
OK
Adding network policy to app rpaas_c2c_cat in org RPAAS / space monitor-stg as sv-ops-rpaas-mon...
OK
Restarting app rpaas_c2c_cat in org RPAAS / space monitor-stg as sv-ops-rpaas-mon...

Stopping app...

Waiting for app to start...

name:                rpaas_c2c_cat
requested state:     started
instances:           1/1
isolation segment:   stg
usage:               64M x 1 instances
routes:
last uploaded:       Mon 02 Jul 08:40:33 UTC 2018
stack:               cflinuxfs2
buildpack:           php 4.3.41
start command:       $HOME/.bp/bin/start

     state     since                  cpu    memory         disk           details
#0   running   2018-07-02T12:40:34Z   1.6%   16.4M of 64M   172.2M of 1G
Restarting app rpaas_c2c_dog in org RPAAS / space monitor-stg as sv-ops-rpaas-mon...

Stopping app...

Waiting for app to start...

name:                rpaas_c2c_dog
requested state:     started
instances:           1/1
isolation segment:   stg
usage:               64M x 1 instances
routes:
last uploaded:       Mon 02 Jul 08:40:36 UTC 2018
stack:               cflinuxfs2
buildpack:           php 4.3.41
start command:       $HOME/.bp/bin/start

     state     since                  cpu    memory         disk           details
#0   running   2018-07-02T12:40:41Z   2.3%   16.1M of 64M   172.2M of 1G
this is cat IP CF_INSTANCE_INTERNAL_IP=10.255.5.166
this is dog IP CF_INSTANCE_INTERNAL_IP=10.255.74.33
nc: connect to 10.255.74.33 port 8080 (tcp) failed: Connection refused
nc: connect to 10.255.74.33 port 8080 (tcp) failed: Connection refused
nc: connect to 10.255.74.33 port 8080 (tcp) failed: Connection refused
nc: connect to 10.255.74.33 port 8080 (tcp) failed: Connection refused
nc: connect to 10.255.74.33 port 8080 (tcp) failed: Connection refused
nc: connect to 10.255.74.33 port 8080 (tcp) failed: Connection refused

Here is the Destination iptables Forward chain:

$  sudo iptables -S FORWARD
-P FORWARD ACCEPT
-A FORWARD -j overlay--491d9a04-9a99-4741-
-A FORWARD -j vpa--1530535237
-A FORWARD -s 10.255.74.33/32 -o eth0 -j netout--491d9a04-9a99-4741-6
-A FORWARD -j overlay--978bda5e-8d08-4d20-
-A FORWARD -s 10.255.74.3/32 -o eth0 -j netout--978bda5e-8d08-4d20-6

- As you can see, timestamp is similar as when the dest_container was started, so it was recreated obviously, and overlay comes before vpa causing the failure. @christianang @adobley

**Comment by christianang** [comment] 2018-07-03 01:13
What I believe is happening is when you create the application and the policy around the same time there is a race on the diego-cell:

1. vxlan-policy-agent sees the new policy and recreates the `vpa` chain
2. cni-wrapper-plugin is called to create the networking bits e.g iptables are written for the `overlay` chain

If the vxlan-policy-agent goes first it will create the `vpa` chain and later on the `overlay` chain is added above breaking c2c. Since the vxlan-policy-agent rewrites iptable rules on policy changes the vpa chain won't be re-inserted to the top.

We will have to make some changes to the vxlan-policy-agent or cni-wrapper-plugin to mitigate against this race.

**Comment by christianang** [comment] 2018-07-05 16:32
We have updated silk release to always append the overlay rules (so it shouldn't ever be added above the vpa rule): https://github.com/cloudfoundry/silk-release/commit/a0858d6542fe366ca73eea0d2f1337893e978fff.

If you could test this out, let us know if this fixes your issue.

**Comment by iamejboy** [comment] 2018-07-09 02:10
@christianang I confirmed that issue was gone after I deployed the updated silk-release. The test script is running for almost 3 days now and the issue has not been replicated. How soon can this be available officially?

**Comment by tylerschultz** [comment] 2018-07-10 20:51
@iamejboy We hope to release sometime before the end of the week. Thanks for getting back to us.

**Comment by christianang** [comment] 2018-07-20 18:34
@iamejboy we cut 2.10.0 release that has the changes you need. I'll be closing this issue.

**Closed by christianang** 2018-07-20 18:34 UTC
Labels: accepted
