### ISSUE TITLE
vxlan-policy-agent won't start due to policy-server SQL error

### ISSUE THREAD

**Issue by pusherofbrooms** [cloudfoundry/cf-networking-release#79] opened 2020-06-15 12:23 UTC
## Issue
When starting up "vxlan-policy-agent" on our diego cells, we are getting the following error:
```
{"timestamp":"2020-06-15T11:58:14.233874801Z","level":"error","source":"cfnetworking.vxlan-policy-agent","message":"cfnetworking.vxlan-policy-agent.policy-client.http-client","data":{"body":"{\"error\": \"database read failed\"}","code":500,"error":"database read failed","session":"1"}}
{"timestamp":"2020-06-15T11:58:14.233926043Z","level":"error","source":"cfnetworking.vxlan-policy-agent","message":"cfnetworking.vxlan-policy-agent.policy-client-get-policies","data":{"error":"http status 500: database read failed"}}
```
Tracing this back to the policy-server (and policy-server-internal) on the api instances, we see the following error:
```
{"timestamp":"2020-06-15T11:57:57.869324360Z","level":"error","source":"cfnetworking.policy-server","message":"cfnetworking.policy-server.metric-getter","data":{"error":"listing all: sql: Scan error on column index 2, name \"guid\": converting NULL to string is unsupported","source":"totalPolicies"}}
```
This set of errors is causing vxlan-policy-agent, and by extension, rep not to start on the cells.

## Context
We are using cf-deployment v12.45.0 which includes cf-networking-release 2.28.0

## Steps to Reproduce
I'm not sure how to reproduce this I haven't found the table with the erroneous NULL value.

## Expected result

vxlan-policy-agent should start without error. policy-server should not throw SQL errors.

## Current result

Described under the issue.

**Comment by pusherofbrooms** [comment] 2020-06-15 15:42
I've done some database spelunking in our policy database. Below are some of my findings:
```
mysql> select count(*) from groups where guid is NULL;
+----------+
| count(*) |
+----------+
|   128785 |
+----------+
1 row in set (0.05 sec)
```
so our group table seems to have about 2289 rows which have guids and 128785 rows where the guid is NULL.

I notice that in the `destinations` and `policies` tables, there are no group id's which have null guids.

**Comment by pusherofbrooms** [comment] 2020-06-15 16:24
on a handful of our api servers, the `policy-server` stdout log contained the following just before the `converting NULL to string` error started.
```
{"timestamp":"2020-06-11T17:14:48.580105874Z","level":"error","source":"cfnetworking.policy-server","message":"cfnetworking.policy-server.request_c9f0401f-c9e1-4976-5e5e-af20f862d28b::050f4b83-df90-4cef-695f-b81555850fd7.create-policies.database create failed","data":{"error":"creating policy: Error 1213: Deadlock found when trying to get lock; try restarting transaction","method":"POST","request":"/networking/v1/external/policies?%3Aversion=v1\u0026","request_guid":"c9f0401f-c9e1-4976-5e5e-af20f862d28b::050f4b83-df90-4cef-695f-b81555850fd7","session":"6687.2"}}
```

**Comment by pusherofbrooms** [comment] 2020-06-15 18:32
I've been observing the behavior of the `groups` table. It looks like when a new policy is added, the first row which has a `NULL` guid in the table (ordered by `id`) is replaced. If this problem is hard to trace, would a quick solution be to delete all of the rows with a `NULL` guid, or will that action break something else?

**Comment by mcwumbly** [comment] 2020-06-15 19:11
hey @pusherofbrooms, @tcdowney and I are taking an initial look at this. I don't have immediate answers for you, but I did want to respond to this question:

>  If this problem is hard to trace, would a quick solution be to delete all of the rows with a `NULL` guid, or will that action break something else?

No, I don't think this would be a good idea.  The groups table is pre-seeded with a bunch of rows that have `NULL` values for `guid` that are then "claimed" by any application referenced in a policy when policies are created.

It is normal to have rows with `NULL` values.

Will follow up when we have had a chance to look a bit closer...

**Comment by mcwumbly** [comment] 2020-06-15 19:41
Hey @pusherofbrooms - we have found a way to reproduce what looks like it may be the issue you are seeing by setting a `group.guid` to `NULL` that is referenced by a policy. I am not sure how this could happen in real life, but perhaps that is what you're seeing.

To check whether you have any data in this state, you can run this query:

```
select * from policies where destination_id in (select id from groups where guid is NULL) or group_id in (select id from groups where guid is NULL);
```

In a healthy database, that should return `0` records. What do you see?

**Comment by pusherofbrooms** [comment] 2020-06-16 10:13
First, to answer your question, the query returns `10276 rows in set`. There are a total of 10286 rows in the policies table.

Does this query have a bug? I wouldn't expect destination_id to line up with the groups, I'd expect it to line up with the destinations table, id column. When I just query for the group_id, I get:
```
mysql> select * from policies where  group_id in (select id from groups where guid is NULL);
Empty set (0.00 sec)
```
The destinations table also has a reference to the group_id. I checked that relation as well:
```
mysql> select * from destinations where  group_id in (select id from groups where guid is NULL);
Empty set (0.00 sec)
```

**Comment by tcdowney** [comment] 2020-06-16 16:57
The query was a simplified version of this that we thought might point out bad data:
https://github.com/cloudfoundry/cf-networking-release/blob/1ad46732357da571d60d4d0607b223009abed758/src/policy-server/store/store.go#L319-L334

It might be worth just trying to replicate that query in raw SQL and executing it.

**Comment by pusherofbrooms** [comment] 2020-06-16 17:21
That helps. I may have found the culprit:

```
mysql> select
    ->   src_grp.guid,
    ->   src_grp.id,
    ->   dst_grp.guid,
    ->   dst_grp.id,
    ->   destinations.port,
    ->   destinations.start_port,
    ->   destinations.end_port,
    ->   destinations.protocol
    -> from policies
    ->   left outer join groups as src_grp on (policies.group_id = src_grp.id)
    ->   left outer join destinations on (destinations.id = policies.destination_id)
    ->   left outer join groups as dst_grp on (destinations.group_id = dst_grp.id)
    -> where src_grp.guid is NULL or dst_grp.guid is NULL;
+--------------------------------------+------+------+------+------+------------+----------+----------+
| guid                                 | id   | guid | id   | port | start_port | end_port | protocol |
+--------------------------------------+------+------+------+------+------------+----------+----------+
| b8e46b6a-46e9-4dde-9678-a9f6c8b61de7 | 1038 | NULL | NULL | NULL |       NULL |     NULL | NULL     |
+--------------------------------------+------+------+------+------+------------+----------+----------+
1 row in set (0.05 sec)
```
I'll do some research into this app and sort out what is going on here.

**Comment by tcdowney** [comment] 2020-06-16 17:26
Yeah, removing that policy would likely resolve the error. I think you'd have to delete it using SQL since the policy-server can't even read it. Now why is the destination for it missing -- I have no clue.

Did this start occurring after an upgrade? Or anything else interesting happen?

**Comment by pusherofbrooms** [comment] 2020-06-16 17:38
Like I said in the description, just before the errors started, some of the policy servers complained about a deadlock, but I don't have other data about the event. Whatever caused the deadlock may have caused this.

I did more spelunking in the database. There may be more cleanup to do:

Searching for the group guid from the above query:
```
mysql> select * from groups where guid = 'b8e46b6a-46e9-4dde-9678-a9f6c8b61de7';
+------+--------------------------------------+------+
| id   | guid                                 | type |
+------+--------------------------------------+------+
| 1038 | b8e46b6a-46e9-4dde-9678-a9f6c8b61de7 | app  |
+------+--------------------------------------+------+
1 row in set (0.00 sec)
```
This application doesn't exist so some sort of orphan group. I searched the policies for that group_id:
```
mysql> select * from policies where group_id = 1038;
+--------+----------+----------------+
| id     | group_id | destination_id |
+--------+----------+----------------+
| 212620 |     1038 |          51919 |
| 212621 |     1038 |          51958 |
+--------+----------+----------------+
2 rows in set (0.00 sec)
```
and then in destinations:
```
mysql> select * from destinations where id in (51919, 51958);
+-------+----------+------+----------+------------+----------+
| id    | group_id | port | protocol | start_port | end_port |
+-------+----------+------+----------+------------+----------+
| 51919 |      984 | 8080 | tcp      |       8080 |     8080 |
+-------+----------+------+----------+------------+----------+
1 row in set (0.00 sec)
```
interesting that `51958` doesn't exist in destinations.
Then I searched for the group id `984`:
```
mysql> select * from groups where id = 984;
+-----+--------------------------------------+------+
| id  | guid                                 | type |
+-----+--------------------------------------+------+
| 984 | c958b9ec-d40f-4a58-8a2a-74782b2a3ab3 | app  |
+-----+--------------------------------------+------+
1 row in set (0.00 sec)
```
This app also doesn't exist.

So what sort of cleanup would you suggest here? Will it be sufficient to remove the orphaned policy with the id `212621`?

**Comment by mcwumbly** [comment] 2020-06-16 18:11
These "stale policies" for apps that no longer exist are cleaned up periodically according to this spec property:

https://github.com/cloudfoundry/cf-networking-release/blob/396e60bd8af26409909e6267df090034f867589c/jobs/policy-server/spec#L55-L57

But that may fail in your current situation.  So the presence of other policies that reference apps that no longer exist may still just be a symptom of the other issue.

I'd try deleting the one policy you found above first, and see if that resolves the problem before doing any other manual cleanup.

**Comment by pusherofbrooms** [comment] 2020-06-16 18:24
after a snapshot of the db, I did
```mysql> select * from policies where id = 212621;
+--------+----------+----------------+
| id     | group_id | destination_id |
+--------+----------+----------------+
| 212621 |     1038 |          51958 |
+--------+----------+----------------+
1 row in set (0.00 sec)

mysql> delete from policies where id = 212621;
Query OK, 1 row affected (0.01 sec)
```
and the `vxlan-policy-agent` and `rep` on the failed cell came up.

This problem came up about 2 weeks after our last upgrade, so I suspect some other event precipitated the orphaned policy.

**Comment by KauzClay** [comment] 2020-06-17 17:31
Hey @pusherofbrooms , 

Just wanted to follow up a bit. I'm interpreting the following line
> and the vxlan-policy-agent and rep on the failed cell came up. The converting NULL to string is unsupported error no longer shows up in the logs.

means you aren't seeing the issues anymore?

I am going to close this issue, but feel free to reopen if there is more to be addressed.

As for this mystery event that might have come before this orphaned policy and got you into this state, there isn't too much we can help with given limited information. However, if it happens again, please open another issue with us! The more information you can collect around the event, the better.

Thanks,
@KauzClay

**Comment by ameowlia** [comment] 2021-04-02 16:07
Hi @pusherofbrooms, 

We've run into this issue again and I have dug a little deeper. 

## **Hypothesis**
Is this happening because either...
1. a policy is created without a destination
2. OR a destination is deleted and the policy isn't (👈  I think it is this one)

## Learnings
**Destinations are only created in one case and in one place**
[Case 1: when a user manually creates a policy](https://github.com/cloudfoundry/cf-networking-release/blob/develop/src/policy-server/store/store.go#L94-L124). Before it deletes the destination it [checks to make sure that an identical one doesn't exist already in the same sql query that inserts it](https://github.com/cloudfoundry/cf-networking-release/blob/develop/src/policy-server/store/store.go#L94-L124). Everything is within a transaction, I don't see any conditions here that would lead to a policy being created without a destination. I don't think the issue is coming from the "create" case.

**Destinations are only deleted in two cases and in one place.** 
Case 1: When a user manually deletes a policy. Case 2: When a user deletes an app that has a policy and then the policy-pruning cycle cleans up the policy. Both cases result in [this "deleteWithTx" ](https://github.com/cloudfoundry/cf-networking-release/blob/3510a86989a30ffc235538574415dd65e9485e3c/src/policy-server/store/store.go#L126-L193)function being called. I believe this function is the ONLY place we [call delete on a destination](https://github.com/cloudfoundry/cf-networking-release/blob/3510a86989a30ffc235538574415dd65e9485e3c/src/policy-server/store/store.go#L176).

**There may be a race condition with the delete case**
[ Relevant code here](https://github.com/cloudfoundry/cf-networking-release/blob/3510a86989a30ffc235538574415dd65e9485e3c/src/policy-server/store/store.go#L171-L180) 
1. line 171: we check to see how many policies are using the destination before we delete it.
2. line 175: Then we check if that number is 0
3. RACE CONDITION: a different user adds a policy (named "second-policy") using that destination
4. line 176: If that number is 0, then we delete the destination 
5. Now the "second-policy" exists, but the destination for it does not.

This seems like it would happen rarely. However the [prune cycle](https://github.com/cloudfoundry/cf-networking-release/blob/3510a86989a30ffc235538574415dd65e9485e3c/jobs/policy-server/spec#L55-L57) happens every hour and if there is an automated process (CI?) adding these policies constantly then maybe it would happen more often. The same type of race condition could happen with groups as well [in this code](https://github.com/cloudfoundry/cf-networking-release/blob/3510a86989a30ffc235538574415dd65e9485e3c/src/policy-server/store/store.go#L195-L214). This is my best guess of root cause so far.

**Mysql and psql behave differently**
When investigating this, I tried to duplicate this in a unit test and I couldn't because I kept getting a `insert or update on table "policies" violates foreign key constraint "policies_destination_id_fkey"` error anytime I tried to manually change the destination_id to one that didn't exist or delete a destination that had a policy. However, when I tried on my dev environment, I could. Turns out psql has a stronger foreign key constraint than mysql does.

**Once it is in a bad state, it does not clean it up**
Like I said above, there is a policy pruning cycle that happens [every hour](https://github.com/cloudfoundry/cf-networking-release/blob/3510a86989a30ffc235538574415dd65e9485e3c/jobs/policy-server/spec#L55-L57). However, if a [policy is in a bad state and does not have a destination then it does clean up that policy](https://github.com/cloudfoundry/cf-networking-release/blob/3510a86989a30ffc235538574415dd65e9485e3c/src/policy-server/store/store.go#L155-L156). I am not sure why this is. Maybe we thought this would never happen? 

## Possible Fixes
1. 👉  (My favorite): Add a foreign key constraint for mysql dbs to match the psql one. This might results in errors during race conditions, but those errors should be recoverable. However, before we do this work, I would want to double check that everyone who ran into the error is in fact running mysql and not psql.
OR
2. Clean up policies during the prune cycle, especially if they are malformed and missing destinations or groups. If we did _only_ this it could still result in an hour of downtime before the prune cycle fixed things --- not great.
3. Make the listing endpoint more resilient so that it lists only valid policies (ie. hide the error from sight). If we did _only_ this it could still result in db cruft with bad policies hanging out there.

## Questions
❓ ~~Are you using mysql or psql?~~ (I see you are using mysql)
❓ How are you using network policies? Do you set them once manually and then leave them? Do you have a CI constantly updating?

**Comment by ameowlia** [comment] 2021-04-13 19:11
Fixed in https://github.com/cloudfoundry/cf-networking-release/releases/tag/2.36.0

**Closed by ameowlia** 2021-04-13 19:11 UTC
Labels: unscheduled

**Comment by pusherofbrooms** [comment] 2021-04-27 11:40
Fyi, we ran into this problem again today, but it's on a version before the above commits. We'll keep you informed after we upgrade if this comes back.

**Comment by ameowlia** [comment] 2021-04-27 15:27
Thanks @pusherofbrooms! Please let us know!
