### ISSUE TITLE
C2C DNS lookups are case-sensitive

### ISSUE THREAD

**Issue by reid47** [cloudfoundry/cf-networking-release#78] opened 2020-05-27 00:25 UTC
## Issue

It seems that hostnames on internal routes are case-sensitive when used in c2c networking.

## Context

We recently made a small change to the v7 CLI to lowercase hostnames that are given to the `map-route` command before sending them to CAP. A seemingly small, innocent change: https://github.com/cloudfoundry/cli/commit/c83198772aaff96fa3d18df495af333b5b2af447

This caused a CATs test to fail, and I found some interesting behavior when investigating. In the failing test, we do the following:

1. Push a backend app and map an internal route to it (which got lowercased, like `cats-1-host.apps.internal`)
1. Push a frontend app that behaves like a proxy
1. Add a network policy to allow the frontend app to talk to the backend app (`cf add-network-policy … --protocol tcp --port 8080`)
1. Curl the frontend proxy with a request like: `curl -k -H Expect: -s http://CATS-1-APP-FRONT-89d91a1f93c9077c.nopa.cli.fun/proxy/CATS-1-HOST-7c9c9cbaacf08282.apps.internal:8080`
1. Expect the proxy to work (hitting the backend app).

Instead, the proxying fails, and the backend returns an error like:
```
request failed: Get http://CATS-1-HOST-7c9c9cbaacf08282.apps.internal:8080: dial tcp: lookup CATS-1-HOST-7c9c9cbaacf08282.apps.internal on <ip address>:53: no such host
```

Note that in that proxy request, **the capitals are preserved**. We can get the test to pass either by reverting the lowercasing change on the CLI side, or by changing the proxy request to look like `.../proxy/cats-1-host-...` (lowercase hostname).

## Steps to Reproduce

Make sure you're targeting some space on a CF that has an internal domain (e.g. `apps.internal`).

1. Use `cf push frontend` to push the frontend proxy app found here: https://github.com/cloudfoundry/cf-acceptance-tests/tree/master/assets/proxy

1. Use `cf push backend --no-route` to push the simple app found here: https://github.com/cloudfoundry/cf-acceptance-tests/tree/master/assets/hello-world

1. Use `cf map-route backend apps.internal --hostname wow` to create and map the internal route `wow.apps.internal` to the backend app

1. Use `cf add-network-policy frontend backend --protocol tcp --port 8080` to add a c2c networking policy from the frontend to the backend.

## Expected result

We should now be able to successfully proxy to the backend app, and the casing of the hostname shouldn't matter:

```
→ curl frontend.nopa.cli.fun/proxy/wow.apps.internal:8080
Hello, world!

→ curl frontend.nopa.cli.fun/proxy/WOW.apps.internal:8080
Hello, world!
```

## Current result

Passing a hostname that doesn't match in case doesn't work:

```
→ curl frontend.nopa.cli.fun/proxy/wow.apps.internal:8080
Hello, world!

→ curl frontend.nopa.cli.fun/proxy/WOW.apps.internal:8080
request failed: Get http://WOW.apps.internal:8080: dial tcp: lookup WOW.apps.internal on 169.254.0.2:53: no such host

→ curl frontend.nopa.cli.fun/proxy/Wow.apps.internal:8080
request failed: Get http://Wow.apps.internal:8080: dial tcp: lookup Wow.apps.internal on 169.254.0.2:53: no such host
```

## Possible Fix

Not sure :(

## Additional Context

Here's the exact test that was failing: https://github.com/cloudfoundry/cf-acceptance-tests/blob/cli-v7-cats-new-features/service_discovery/service_discovery.go

I was using the V7 CF CLI, but it shouldn't matter for this. The only relevant difference from V6 is that in V6, creating the network policy would look like: `cf add-network-policy frontend --destination-app backend --protocol tcp --port 8080`

**Comment by KauzClay** [comment] 2020-06-08 18:03
Hi @reid47 ,

Thanks for the detailed issue! The reproduction steps are great. 

This all makes sense and we think this is worthwhile, so we will prioritize this to get fixed.

Thanks!
@KauzClay  and @christianang

**Comment by jrussett** [comment] 2020-07-07 16:53
Hi @reid47,

Thanks again for this issue. 

I'm closing this issue because the requisite fixes are now present in the newly cut [release 2.31.0](https://github.com/cloudfoundry/cf-networking-release/releases/tag/2.31.0). 🎉🥳

Thanks!
@jrussett

**Closed by jrussett** 2020-07-07 16:53 UTC
Labels: scheduled
